# ~/.circleci/config.yml
version: 2.1
 jobs:
  test-maven:
    working_directory: ~/rr
    docker:
      - image: maven:3.5.0-jdk-9

    steps:
      - checkout

      - restore_cache:
          key: rr-{{ checksum "pom.xml" }}

      - run: mvn test

      - save_cache:
          paths:
            - ~/.m2
          key: rr-{{ checksum "pom.xml" }}

      - store_test_results:
          path: target/surefire-reports

#-----------------------------------------------------------------
build-maven:
    working_directory: ~/rr
    docker:
      - image: maven:3.5.0-jdk-9

    steps:
      - checkout

      - restore_cache:
          key: rr-{{ checksum "pom.xml" }}

      - run: mvn package

      - save_cache:
          paths:
            - ~/.m2
          key: rr-{{ checksum "pom.xml" }}

      - store_test_results:
          path: target/ 
#------------------------------------------------------------------------------
site-maven:
    working_directory: ~/rr
    docker:
      - image: maven:3.5.0-jdk-9

    steps:
      - checkout

      - restore_cache:
          key: rr-{{ checksum "pom.xml" }}

      - run: mvn site

      - save_cache:
          paths:
            - ~/.m2
          key: rr-{{ checksum "pom.xml" }}

      - store_test_results:
          path: target/site
#--------------------------------------------------------------------------------------
deploy-maven:
    working_directory: ~/rr
    docker:
      - image: maven:3.5.0-jdk-9

    steps:
      - checkout

      - restore_cache:
          key: rr-{{ checksum "pom.xml" }}

      - run: mvn surefire:test test

      - save_cache:
          paths:
            - ~/.m2
          key: rr-{{ checksum "pom.xml" }}

      - store_test_results:

          path: target/site
# work flow

workflows:
   verson : 2.1
     workflow:
        jobs:
          - test-maven
          - build-maven
          - site-maven
             requires:
                - test-maven
                - build-maven
          - deploy-maven
                requires:
                 - site-maven
